name: Release

# ----------------------------------------------------------------- #
# - release_backend tag pushed  --> backend image pushed to azure   #
# - release_frontend tag pushed --> frontend image pushed to azure  #
# - release tag pushed          --> both images pushed to azure     #
# ----------------------------------------------------------------- #

on:
  push:
    tags:
      - 'release_backend'
      - 'release_frontend'
      - 'release'

env:
  AZURE_CONTAINER_REGISTRY: dbsdockerregistry.azurecr.io
  RELEASE_FRONTEND: ${{ (github.ref == 'refs/tags/release') || (github.ref == 'refs/tags/release_frontend') }}
  RELEASE_BACKEND: ${{ (github.ref == 'refs/tags/release') || (github.ref == 'refs/tags/release_backend') }}

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - name: Build frontend project, create push backend docker image to Azure registry
        run: echo "hi"
        if: ${{ env.RELEASE_FRONTEND }}
